// AUTO-GENERATED by scripts/generate-banner-slides.mjs — do not edit by hand.
// Add, rename or remove images in public/images/home-banner-slider/ and rebuild.

/** The banner artwork carries its own copy, so a slide is just the image. */
export interface HeroSlide {
  image: string;
  alt: string;
}

/** Every image in the slider folder, in natural filename order. */
export const HOME_BANNER_SLIDES: readonly HeroSlide[] = [
  {
    image: 'images/home-banner-slider/large-pizza-zinger-deal.png',
    alt: 'Large pizza zinger deal',
  },
  {
    image: 'images/home-banner-slider/medium-pizza-zinger-deal.png',
    alt: 'Medium pizza zinger deal',
  },
];
