// AUTO-GENERATED by scripts/generate-banner-slides.mjs — do not edit by hand.
// Add, rename or remove images in public/images/home-banner-slider/ and the dev server picks them up.

/** The banner artwork carries its own copy, so a slide is just the image. */
export interface HeroSlide {
  image: string;
  alt: string;
}

/** Every image in the slider folder, in natural filename order. */
export const HOME_BANNER_SLIDES: readonly HeroSlide[] = [
  {
    image: 'images/home-banner-slider/banner-1.png',
    alt: 'Banner 1',
  },
  {
    image: 'images/home-banner-slider/banner-2.png',
    alt: 'Banner 2',
  },
  {
    image: 'images/home-banner-slider/banner-3.png',
    alt: 'Banner 3',
  },
  {
    image: 'images/home-banner-slider/banner-4.png',
    alt: 'Banner 4',
  },
  {
    image: 'images/home-banner-slider/banner-5.png',
    alt: 'Banner 5',
  },
  {
    image: 'images/home-banner-slider/banner-6.png',
    alt: 'Banner 6',
  },
];
